#!/bin/bash

# Copyright 2015 Insight Data Science
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# check input arguments
if [ "$#" -ne 4 ]; then
    echo "Please specify cluster name, technology and mode (cluster or single)!" && exit 1
fi

CONFIGURATOR_ROOT=$(dirname ${BASH_SOURCE})/..

source ${CONFIGURATOR_ROOT}/util.sh

# get input arguments [aws region, pem-key location]
MASTER_DNS=$1
WORKER_DNSES=$2
TECHNOLOGY=$3

PUBLIC_DNSES=("$MASTER_DNS" "$WORKER_DNSES")

script="${CONFIGURATOR_ROOT}/install/download_tech"
args="${TECHNOLOGY}"

echo 'before loop in cluster_download'
for dns in ${PUBLIC_DNSES[@]}; do
  echo -e "${color_yellow}Checking node ${dns}${color_norm}"
  echo "running script ${dns} ${script} ${args}"
  run_script_on_node ${dns} ${script} ${args} &
done

wait

echo "${TECHNOLOGY} installed!"
