#!/bin/bash

set -o errexit

CONFIGURATOR_ROOT=$(dirname "${BASH_SOURCE}")
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:=us-west-2}
REM_USER=${REM_USER:=ubuntu}

source ${CONFIGURATOR_ROOT}/util.sh

nargs="$#"

if [ ${nargs} == 0 ]; then
  echo "Usage: configurator [options] <command> [parameters]"
  echo "configurator: error: too few arguments"
  echo "use the -h option for available commands"
  exit 1
fi

while getopts ":h" opt; do
  case ${opt} in
    h)
      echo "configurator"
      echo "    - install"
      exit 1
      ;;

    *)
      echo "Invalid option flag: -${OPTARG}"
      exit 1
      ;;
  esac
done

args=("$@")
command=${args[0]}
parameters=${args[@]:1}
nfargs=$(echo ${parameters} | wc -w)

case ${command} in
  install)
    if [[ "${nfargs}" -eq "5" ]]; then
      PARAMETER_ARR=(${parameters})
      TECHNOLOGY=${PARAMETER_ARR[0]}
      MASTER_DNS=${PARAMETER_ARR[1]}
      WORKER_DNSES=${PARAMETER_ARR[2]}
      MASTER_PRIVATE_HOSTNAME=${PARAMETER_ARR[3]}
      WORKERS_PRIVATE_HOSTNAMES=${PARAMETER_ARR[4]}

      DEP_ROOT_FOLDER=/usr/local/

      case ${TECHNOLOGY} in
        aws)
          echo "Passing AWS credentials to ${MASTER_DNS}"
          ${CONFIGURATOR_ROOT}/config/pass_aws_cred ${MASTER_DNS}
          ;;

        environment)
          echo "Setting up base environment packages on ${MASTER_DNS} and ${WORKER_DNSES}"
          ${CONFIGURATOR_ROOT}/install/environment/install_env_cluster.sh ${MASTER_DNS} ${WORKER_DNSES}
          ;;

        kafka|zookeeper)
          get_dependencies >> /dev/null
          install_tech "cluster"
          ;;

        ssh)
          echo "Setting up passwordless SSH on ${MASTER_DNS} and ${WORKER_DNSES}"
          echo ${MASTER_DNS}
          ${CONFIGURATOR_ROOT}/config/ssh/setup_passwordless_ssh.sh ${MASTER_DNS} ${WORKER_DNSES} ${MASTER_PRIVATE_HOSTNAME} ${WORKERS_PRIVATE_HOSTNAMES}
          ;;

        *)
          echo "Invalid technology to install."
          exit 1
          ;;
      esac
    else
      echo "Invalid number of arguments"
      echo "Usage: configurator install <technology> <master-dns> <worker-dns-1,worker-dns-2,...>"
    fi
    ;;
  service)
    if [[ "${nfargs}" -eq "4" ]]; then
      PARAMETER_ARR=(${parameters})
      ACTION=${PARAMETER_ARR[0]}
      TECHNOLOGY=${PARAMETER_ARR[1]}

      MASTER_DNS=${PARAMETER_ARR[2]}
      WORKER_DNSES=${PARAMETER_ARR[3]}

      case $TECHNOLOGY in
        kafka|zookeeper)
          ROOT_FOLDER=/usr/local/
          INSTALL_PATH="folder"
          service_action
          ;;
        *)
          echo "Invalid service to ${ACTION}."
          exit 1
          ;;

      esac
    else
      echo "Invalid number of arguments"
      echo "Usage: peg service <cluster-name> <technology> <start|stop>"
    fi
    ;;
esac
